### PR TITLE
Add inception-v4 to supported models

### PR DESCRIPTION
**Pull request by kuke**
```
-----------  Configuration Arguments -----------
a: 0.0
b: 1.0
backend: caffe2
batch_size: 10
expected_decimal: 5
fluid_model: extras/inception_v4.inference.model/
onnx_model: inception_v4.onnx
------------------------------------------------
Inference results for fluid model:
[array([[0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       ...,
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415]], dtype=float32)]


Inference results for ONNX model:
Outputs(_0=array([[0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       ...,
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415],
       [0.0096415, 0.0096415, 0.0096415, ..., 0.0096415, 0.0096415,
        0.0096415]], dtype=float32))


The exported model achieves 5-decimal precision.
```

On flowers dataset. Not validated on TensorRT backend for its `Concat` op implementation doesn't support inputs with different shape

### CODE REVIEW

**Review by varunarora — APPROVED** [review]
Nice! Is the TensorRT `Concat` problem a specific TensorRT problem or was it unsupported in the spec in 1.0.1?

**Comment by kuke** [comment]
It should be the problem of TensorRT. Run unit test of `Concat` op with the tensorrt backend, it will give the error:

```
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 106, in run
    outputs = self.engine.run(inputs)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/tensorrt_engine.py", line 113, in run
    (i, expected_shape, given_shape))
ValueError: Wrong shape for input 0. Expected (1, 4, 5), got (3, 4, 5).
```   

Here the error happens:

https://github.com/PaddlePaddle/paddle-onnx/blob/4d9dd93d05655a4e25fc588569b95ef64e34eeeb/tests/test_concat_op.py#L31-#L36

**Comment by varunarora** [comment]
Yeah just report on their GitHub if you get a chance, and we should be good to go.

**Comment by kuke** [comment]
@varunarora OK. I am going to report this issue.

**Pull request merged**
