### PR TITLE
Change lod_level to legacy_lod_level

### PR DESCRIPTION
**Pull request by co63oc**
修改 lod_level 为 legacy_lod_level

Paddle中已修改
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/framework/framework.proto
image

https://github.com/PaddlePaddle/Paddle/issues/69305

### CODE REVIEW

**Review by wanghuancoder — APPROVED** [review]
LGTM

**Comment by co63oc** [comment]
@Zheng-Bicheng CI已完成需要review下

**Review by Zheng-Bicheng — APPROVED** [review]
LGTM

**Comment by Zheng-Bicheng** [comment]
@co63oc 合入啦，感谢贡献

**Pull request merged**
